<script>
var CONTEXT = "${CONTEXT}";
</script>


<link href="${CONTEXT}/css/default.css?version=${version}" rel="stylesheet" type="text/css" />
<link rel="icon" href="${CONTEXT}/favicon.ico" type="image/x-icon"/>
<link rel="shortcut icon" href="${CONTEXT}/favicon.ico" type="image/x-icon"/>


<link rel="stylesheet" type="text/css" href="${CONTEXT}/js/jquery-easyui-1.5.3/themes/default/easyui.css?version=${version}" />
<link rel="stylesheet" type="text/css" href="${CONTEXT}/js/jquery-easyui-1.5.3/themes/icon.css?version=${version}" />
<link rel="stylesheet" type="text/css" href="${CONTEXT}/css/icons/icon-hamburg.css?version=${version}" />


<script src="${CONTEXT}/js/jquery-easyui-1.5.3/jquery.min.js?version=${version}" type="text/javascript"></script>
<script src="${CONTEXT}/js/jquery-easyui-1.5.3/jquery.easyui.min.js?version=${version}" type="text/javascript"></script>

<script src="${CONTEXT}/js/jquery-easyui-1.5.3/plugins/jquery.dialog.js?version=${version}"  type="text/javascript"></script>
<script src="${CONTEXT}/js/jquery.json.min.js?version=${version}" type="text/javascript"></script>
<script src="${CONTEXT}/js/jquery-easyui-1.5.3/locale/easyui-lang-zh_CN.js?version=${version}" type="text/javascript"></script>
<script src="${CONTEXT}/js/common/jquery.validate.js?version=${version}" type="text/javascript"></script>
<script src="${CONTEXT}/js/common/common.js?version=${version}" type="text/javascript"></script>
