package com.lwx.usm.mapper;

import com.lwx.usm.model.TransactionLock;

public interface TransactionLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_lock
     *
     * @mbggenerated Wed Sep 06 10:04:28 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_lock
     *
     * @mbggenerated Wed Sep 06 10:04:28 CST 2017
     */
    int insert(TransactionLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_lock
     *
     * @mbggenerated Wed Sep 06 10:04:28 CST 2017
     */
    int insertSelective(TransactionLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_lock
     *
     * @mbggenerated Wed Sep 06 10:04:28 CST 2017
     */
    TransactionLock selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_lock
     *
     * @mbggenerated Wed Sep 06 10:04:28 CST 2017
     */
    int updateByPrimaryKeySelective(TransactionLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_lock
     *
     * @mbggenerated Wed Sep 06 10:04:28 CST 2017
     */
    int updateByPrimaryKey(TransactionLock record);
}